### ISSUE TITLE
Close stale PRs opened by dependencies

### ISSUE THREAD

**Issue by timhaines** [dependencies-io/support#11]
If there's already a PR open for a package update, and a new patch release comes out, you get 2 PRs - one for each upgrade.

I think it'd be preferable in the majority of cases to either update the existing PR (maintaining comments and conversation), or close it and open a new one (referencing the old PR that was closed would be awesome).

**Comment by davegaeddert** [comment]
Totally agree with this. I think this would be an awesome thing to add to https://github.com/dependencies-io/pullrequest, which is our little utility that all our actors use to open the actual pull request. I wrote down a few thoughts here if you're curious about specifics: https://github.com/dependencies-io/pullrequest/issues/2 Long story short, I think we'll start by closing the stale PRs instead of trying to update/merge for now.

**Comment by davegaeddert** [comment]
Finally got around to implementing this -- rolling it out to all of our actors now. You can use the `related_pr_behavior: close` setting to enable it. Thanks @timhaines!

![image](https://user-images.githubusercontent.com/649496/32860531-7cf8f98e-ca17-11e7-9f76-ea0b05a74b15.png)

https://github.com/dependencies-io/pullrequest/pull/8
