### ISSUE TITLE
Batch PR structured summary

### ISSUE THREAD

**Issue by shilman** [dependencies-io/support#13]
## Proposal
Include a structured summary at the top of batch PRs, e.g.:

```md
- enzyme-adapter-react-16 from 1.0.1 to 1.0.2 in /
- webpack-hot-middleware from 2.19.1 to 2.20.0 in app/react
- ...

---

[... existing content with details]
```

This improves readability and also makes it easier for other tools to extract useful summaries from the PR (see below for detailed case).

## Storybook case
In Storybook we are generating release changelogs based on merged PRs (using a modified version of https://github.com/lo1tuma/pr-log). Sample: https://github.com/storybooks/storybook/releases/tag/v3.2.13

We switched to using batch PRs which is awesome 💯 . Unfortunately, it makes changelog we generate significantly less useful, e.g. "2 packages updated by dependencies.io" (see the "Dependency Upgrades" section of the changelog above).

If you include the structured update we will parse out the summary section for the purpose of the changelog. We could also parse the existing content, but it would be easier if there was a well-structured summary at the beginning of each PR.

**Comment by davegaeddert** [comment]
@shilman sounds good to me. Cleaning up that content is something I wanted to spend a little more time on -- and knowing that you're using it for automatic changelogs is helpful. Do you have any suggestion as to what the title of the PR should say? Sounds like you may use the summary content anyway, but the title was another place that I thought could be a little more helpful.

Thanks!

**Comment by shilman** [comment]
@davegaeddert I don't have any good ideas about the PR title unfortunately--you could try to inline the first couple packages e.g. "Dependencies.io updated 7 packages (package1, package2, +5 more)" but I don't know how useful that is.

For the PRs that I examined the "details" were not so useful --- is that because those packages didn't include release notes for the version upgrade? Thanks!

**Comment by davegaeddert** [comment]
No problem, we'll see if can come up with anything for the title but it sounds like it's not super critical to your workflow anyway.

The "details" are tracked down through an internal library that tries to find the release info/changelog as best it can. Unfortunately, there aren't too many standards yet for where to put that content and npm doesn't do much to make it easier. So, it's a constantly evolving process to try and improve that and find the most accurate content we can. If you want to point me towards some specific packages + versions that didn't have any content, I can add them to our testing list which is about the only way we can try to track down all the different scenarios and use cases (or see if there was a bug).

We're reworking a couple things on a shared package so that we can get the formatting updated on the lerna actor and also easily add the same behavior (+formatting) to the npm actor (which @hypnosphi thought would also be helpful for storybook). I'll let you guys know when it's ready!

Thanks for the feedback!

**Comment by Hypnosphi** [comment]
> which @Hypnosphi thought would also be helpful for storybook

We actually use it for `docs` package, which is not a part of workspaces

**Comment by shilman** [comment]
@davegaeddert Can you point me at the heuristics for tracking down the changelog information? As somebody who is generating changelogs, and is generally interested in adopting standards if they make sense, I'd love to make sure we are doing it well (I am currently just prepending to CHANGELOG.md in the root).

If you have any opinions on this, I could potentially change how we do it in storybook. Also when I'm happy with our release flow I'll probably write a post on it and possibly OSS the changelog piece, so it could be a small step towards creating a standard or reinforcing an existing one.

Thoughts welcome! And thanks so much for being responsive on the initial request. Much appreciated!

**Comment by davegaeddert** [comment]
The code is currently private, but I can give you the gist of what we do today!

For each release:
- get the "source" API info (for npm, we use `https://registry.npmjs.org/${name}`)
  - some of these APIs (like pypi) have changelog information right there, npm does not in the cases we've seen
  - get the location of the GitHub or GitLab source repo (npm has a "repository" field, so we try that)
    - if it's on GitHub
      - get a list of git tags, try to find the matching version tag
        - if we found a tag, then we check if there is a GitHub Release with content, and if so then we use that
        - if we found a tag but no release, then we check for a changelog/history/releases/readme file and run regular expressions to try to pull out the section with changelog info for our version

So, long story short: first we check the package management API, second we check GitHub Releases, third we do our best to pull it out of the source files. At each one of those steps we try a bunch of different things (formatting of version tags, files and filetypes where people put changelogs, etc.) and as you can imagine, it's not always perfect.

I wish I had a better sense of what direction this is headed or had some more expertise in it -- really seems like something that could use a little standardization! I like the way that you're doing it. My preference would be to see a `CHANGELOG.*` file in a repo, which it seems like we can all do regardless of package system, git hosts, languages, etc. Mirroring that content into GitHub Releases or any other service-specific system seems like a great addition since you can get the content closer to the user (and could/should be automated) but I'm not a big fan of ["only keeping our changelogs in GitHub releases"](https://github.com/zeit/release#why), for example.

I like this too: http://keepachangelog.com/en/1.0.0/

We've got a couple ideas and things in the works for automating that flow based on a `CHANGELOG.md`, and I know there's quite a few things that exist already. Not sure where all of that is headed or if we'll be able to help at all, but I'm all for it if we can! If you know of any discussion about standards around this, I'd love to take a look. I will tell you that I own the domain "release.guide" and think it would be awesome to work with others to start nailing down the "best practices for releasing a ___ package" and eventually some tooling to go with it.

p.s. the new PR formatting is almost ready to go, I'll let you know ;)

**Comment by davegaeddert** [comment]
The formatting has been updated. It will look like this now for batch PRs:
```md
## Overview

The following dependencies have been updated:

- @storybook/addon-actions in `docs` from `3.2.13` to `3.2.14`
- @storybook/addon-links in `docs` from `3.2.13` to `3.2.14`
- @storybook/addons in `docs` from `3.2.13` to `3.2.14`
- @storybook/react in `docs` from `3.2.13` to `3.2.14`
- front-matter in `docs` from `2.2.0` to `2.3.0`
- react-stack-grid in `docs` from `0.5.0` to `0.6.0`

## Details

(changelogs and release notes here)
```

This is subject to change a little bit in terms of wording as we continue to make things more user-friendly, so if you're going to parse out the summary I'd just grab the first bulleted list that you see (group of lines starting with `- `). We'll keep that list in place but the text around it might change (or wording in the list itself).

Let me know if you have any questions on it. [Pullrequest](https://github.com/dependencies-io/pullrequest) is actually the place where the formatting happens now so any updates will be made there.

@shilman I'm going to close this issue. If you want to talk about changelog/release standardization any more feel free to open another issue if it makes sense or just send me an email (dave.gaeddert at dropseed.io).
