### ISSUE TITLE
Support extra fields in version listing

### ISSUE THREAD

**Issue by leesdolphin** [dependencies-io/support#18]
I'm currently writing a Drupal update script and would like to include both the tag and the download URL in my collector given that the tag names sometimes do not match the semver.

A simple solution would be to add a `"metadata": {...}` field which can contain any key/value pairs.

**Comment by davegaeddert** [comment]
Hey @leesdolphin, glad to hear you're working on it! I think we might have to add a field like that for storing extra info (it's come up a couple times now) but so far we've gotten along without it. Could you point me towards an example where the download URL is not predictable? I was just quickly scrolling through the Drupal release feeds you're using and all the ones I spot-checked seemed to use the `version` field in the `download_link` field like this `f'https://ftp.drupal.org/files/projects/drupal-{version}.tar.gz'`. And it seems like the `version` would be the thing to use instead of `tag`...?

Just curious if we can get by without it still or if it's time to add some kind of metadata field to our schema. Thanks!

**Comment by davegaeddert** [comment]
@leesdolphin let me know if you have other thoughts on this. We're in the middle of finalizing a few fields that will be added to the schema soon, and aren't planning on adding this just yet.

**Comment by leesdolphin** [comment]
I've done some more reading into the Drupal information and I agree, the version field is sufficient to rebuild the full URL. 

However on quite a few Drupal projects I work with, the entire Drupal codebase is merged into the tree; rather than extracting it over the top(So `git merge <drupal tag>`), and whilst the tags and versions remain the same for released versions; the same cannot be said for development one.

The other is that the actor now hard-codes the download location of the drupal releases, which IMO is less than ideal.

The obvious alternative is to re-download the version listing in the actor phase to gather that extra information.

**Comment by davegaeddert** [comment]
Closing this for now. Still haven't need to do anything like this yet.
