### ISSUE TITLE
Disable yarn.lock updates

### ISSUE THREAD

**Issue by teeberg** [dependencies-io/support#25]
Is there some configuration for disabling PRs that update the `yarn.lock`? That seems like a risky change, so we would like to disable it and rather update them in a more controlled way.
![image](https://user-images.githubusercontent.com/199071/38042544-80ed2cf8-3269-11e8-848d-86b8eebdeba8.png)

**Comment by davegaeddert** [comment]
You can use `lockfile_updates.enabled`:
```yml
version: 2
dependencies:
- type: js
  lockfile_updates:
    enabled: false
```

https://www.dependencies.io/docs/configuration/

Just curious, what makes them feel risky in your situation? Do you use pretty wide ranges in your package.json?

I guess the way I personally think about it is that the package.json ranges should define what you consider to be "safe", since at any point in time if a developer runs a yarn command that updates everything in the lockfile, you'll get all those updates at that point in time. Does that make sense?

Would love to hear what you think though! We don't intend to dictate the way anybody works, but if we could help arrive on some "best practices" or something based on some general community consensus, I think it'd be useful to at least document those kinds of things (if they're not documented somewhere else already).

**Comment by teeberg** [comment]
I've debugged issues before where a direct dependency of ours didn't correctly pin their dependencies and so we ended up pulling in transitive dependencies that weren't actually supported by the direct dependency and caused issues because of backwards-incompatible changes of the transitive dependency. I do report these back so that other people don't run into similar issues, but they are annoying to debug.

Now check out the latest update to our `yarn.lock` that dependencies.io suggested:
> 115 transitive dependencies were updated, 6 were added, and 5 removed. View the git diff for more details about exactly what changed.

That's 126 package version changes! Maybe I'm kidding myself that I would catch these issues if upgraded individually, but it seems much more likely to break *something* that we wouldn't catch if we upgrade all of those at once.

Assuming that our test suite isn't perfect and every package update needs some targeted manual testing, every package update means some work. That's fine for 1 package, but not for 126.

My ideal workflow would be: Have easy access to a list of all available updates, where, for every single one, I can say "Yes" or "No", where "Yes" would open the PR as you currently do, but "No" would skip that update until there's a new update. Many updates don't bring any functional improvements that I care about, so I'd prefer to decide, based on the changelog, whether I need a specific update, rather than have it dictated on me. That's why we configured dependencies.io to only automatically update a very limited subset of packages, for which we expect our test suite to find issues, since every update takes time away from other work.

**Comment by davegaeddert** [comment]
I see, thanks for the detail.

The first point about one of your direct dependencies not pinning theirs correctly is interesting. I'm not sure what there is to do about that, since it kinda seems like mantainer-error in some ways (either by them or even further up the chain)? I can see how that would be annoying to debug! Do you use [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to resolve it or just try to help push the fix upstream?

> That's 126 package version changes! Maybe I'm kidding myself that I would catch these issues if upgraded individually, but it seems much more likely to break something that we wouldn't catch if we upgrade all of those at once.

This is my biggest complaint about npm, especially being more of a python/pypi user myself. It just seems like a ridiculous amount of dependencies, but I'm sure there are plenty of good arguments both ways.

The way that I *personally* have chosen to deal with this issue on npm/js projects is to just go ahead and accept those `yarn.lock` transitive updates "early and often". I *know* that I'm kidding myself if I think that I'd be better off trying to make those transitive updates individually (if there's even a good way to do so...). And I also know that I probably wouldn't have caught any small problems that could have been introduced, either through automated or manual testing. Hopefully, anything significant would be caught by even a basic test suite and/or a manual spot check. I also like to think that more issues would have been fixed in those 126 transitive changes than introduced.

Not saying that's the best way to deal with it (it has some major issues) but that's where I usually land. So my preference is to have something like dependencies.io keep my lockfile updated daily/weekly. If a minor problem hits production, so be it. It probably would have anyway. And if you get into a daily or weekly  `yarn.lock` update rhythm, the updates stay smaller and are easier to mentally accept.

Maybe some people are on teams or in situations where they have time to go through these little transitive changes with a fine-tooth comb, but that's never been the case for me and I doubt it is for most people.

Thoughts on that?

I also found this which you might be interested in reading at least: https://github.com/yarnpkg/rfcs/pull/54

**Comment by davegaeddert** [comment]
It's been a while, so I'm going to close this for now.
