### ISSUE TITLE
Push-based dependency checks so that users only need to expose package.json, requirements.txt, etc

### ISSUE THREAD

**Issue by ento** [dependencies-io/support#7]
As much as I'd like to jump in and start automating dependency upgrades, I'm hesitant to open up a private company repo to a fledgling service, largely due to security concerns.

Would it be possible to implement a flow like:

- user-controlled periodic tasks push current dependencies to api.dependencies.io/user/project
- dependencies.io runs their awesome algorithm against the dependencies
- dependencies.io opens Pull Requests, pushes to Slack, etc

Alternatively, I might be convinced after seeing how dependencies.io's infrastructure looks like and what security measures are taken.

**Comment by davegaeddert** [comment]
Hey @ento, totally understandable, and thanks for raising the question.

The push-mechanism is an interesting idea. We'll give it some thought, but my first impression is that it's unlikely. We designed the system to be a lot like a typical CI service, where it goes a git clone of the repo. There are a few big benefits of doing it this way, which I may try and write up somewhere...

What's your biggest concern security-wise? Is it that we'll accidentally do something to your repo, like push a bad commit to master? Or is it just that yet-another-service has some kind of API access to your information? All of the above? Something else?

**Comment by ento** [comment]
I think I'm seeing dependencies.io as something like an add-on to the CI setup we have. Something like [codecov](https://docs.codecov.io/docs/about-the-codecov-bash-uploader): accept a subset of a repo and post something useful to the repo in return.

> Or is it just that yet-another-service has some kind of API access to your information? 

Closer to this one: general desire to minimize the surface area of a potential leak. (We don't have any special security compliance requirements.)

**Comment by davegaeddert** [comment]
Ok, good to know.

Totally understand the desire to minimize services which have access to your data. We will give some thought towards what could be done to alleviate concerns there (either in how the product works or just in communication). If there are specific kinds of things that you would like to know and would make you feel more comfortable, let me know.

I will say that we have dealt with those kinds of concerns before, and in truth, they pretty much all disappeared given some time and name recognition. https://pullapprove.com and https://sibbell.com  are both other services of ours which are based on integrating with GitHub. PullApprove especially had a lot of questions like that right off the bat since it was built off the original OAuth integration system which got even more ridiculous amounts of access to repos! I bet it's been at least a year though since anybody voiced that kind of concern, and I don't know for sure but I think it's just because it has somewhat of a reputation at this point (though very few things have changed security-wise). For what it's worth, we've never had any security related-incidents with either of those products to-date.

@ento does knowing about our other products/history/company help in any way? We've been having some internal discussions related to branding, and are considering the idea of creating stronger ties between our company and the different products.

**Comment by davegaeddert** [comment]
Going to close this for now.

**Comment by ento** [comment]
>does knowing about our other products/history/company help in any way? 

I think so!

I recently found this doc in houndci's repo: https://github.com/houndci/hound/blob/master/doc/SECURITY.md

Having access to a something similar write-up will be helpful.

**Comment by davegaeddert** [comment]
Cool, thanks. Totally agree it would be good for us to get something like that in place. I'll make sure it's on the (long) list.

**Comment by ento** [comment]
With all that said, we're probably going to test-drive dependencies.io :)

**Comment by davegaeddert** [comment]
Sounds good, let me know if you have any questions as you do. We've gotten a lot of good feedback so far and have some major improvements coming -- hopefully soon but probably not until after the holidays.
